# Generated by Django 3.0.5 on 2020-04-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200414_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='image',
            field=models.ImageField(default='', upload_to='form_images'),
        ),
    ]
